microservice:
   movie-catelog-service:
      endpoints:
         endpoint:
             geturi: http://movie-info-service/movieInfo/getMovies 
             
microservice1:
   movie-catelog-service:
      endpoints:
         endpoint:
             posturi: http://movie-info-service/movieInfo/addMovies         
